/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompanyConfiguration"];
        put: operations["updateCompanyConfiguration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/nfse/provider-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the dynamic NFSe form policy required by the resolved municipal provider. */
        get: operations["getCompanyNfseProviderInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/operation-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanyFiscalOperationProfiles"];
        put?: never;
        post: operations["createCompanyFiscalOperationProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/operation-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCompanyFiscalOperationProfile"];
        post?: never;
        delete: operations["deleteCompanyFiscalOperationProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/rate-references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanyFiscalRateReferences"];
        put?: never;
        post: operations["createCompanyFiscalRateReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/rate-references/{rate_reference_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCompanyFiscalRateReference"];
        post?: never;
        delete: operations["deleteCompanyFiscalRateReference"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/tax-rule-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanyFiscalTaxRuleSets"];
        put?: never;
        post: operations["createCompanyFiscalTaxRuleSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/tax-rule-sets/{tax_rule_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCompanyFiscalTaxRuleSet"];
        post?: never;
        delete: operations["deleteCompanyFiscalTaxRuleSet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanyDocuments"];
        put?: never;
        post: operations["createCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompanyDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/{external_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/{external_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["correctCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/direct/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCompanyDirectDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/direct/documents/xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transmitCompanyDirectXml"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProducts"];
        put?: never;
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProduct"];
        put: operations["updateProduct"];
        post?: never;
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/takers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTakers"];
        put?: never;
        post: operations["createTaker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/takers/{taker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTaker"];
        put: operations["updateTaker"];
        post?: never;
        delete: operations["deleteTaker"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWebhooks"];
        put?: never;
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateWebhook"];
        post?: never;
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateWebhookSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIntegrationMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIntegrationBilling"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compatibility alias for the integration client's default company. */
        get: operations["listDefaultCompanyDocuments"];
        put?: never;
        /** @description Compatibility alias for the integration client's default company. */
        post: operations["createDefaultCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compatibility alias for the integration client's default company. */
        post: operations["previewDefaultCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefaultCompanyDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{external_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelDefaultCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{external_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["correctDefaultCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/direct/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compatibility alias for direct transmission on the integration client's default company. */
        post: operations["createDefaultCompanyDirectDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/direct/documents/xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compatibility alias for direct XML transmission on the integration client's default company. */
        post: operations["transmitDefaultCompanyDirectXml"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configuration/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefaultCompanyConfiguration"];
        put: operations["updateDefaultCompanyConfiguration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nfse/provider-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compatibility alias for the integration client's default company. */
        get: operations["getDefaultCompanyNfseProviderInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DocumentRequest: {
            external_id?: string;
            /** @enum {string} */
            document_type: "nfe" | "nfce" | "nfse";
            municipio?: string;
            payload: {
                [key: string]: unknown;
            };
            metadata?: {
                [key: string]: unknown;
            };
        };
        NfseProviderInfo: {
            provider_key?: string | null;
            municipio?: string | null;
            resolution_source?: string | null;
            provider_metadata?: {
                [key: string]: unknown;
            };
            warnings?: string[];
            form_policy?: components["schemas"]["NfseFormPolicy"];
        };
        NfseFormPolicy: {
            provider_key?: string | null;
            layout_family?: string | null;
            municipio_ibge?: string | null;
            municipio_nome?: string | null;
            policy_source?: string;
            required_fields?: components["schemas"]["NfsePolicyField"][];
            visible_fields?: components["schemas"]["NfsePolicyField"][];
            default_values?: {
                [key: string]: string;
            };
            field_schema?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            labels?: {
                [key: string]: string;
            };
            hints?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        NfsePolicyField: "service.municipal_code" | "service.national_tax_code" | "service.nbs" | "service.cnae_code" | "service.activity_code" | "prestador.op_simp_nac";
    };
    responses: {
        /** @description JSON resource response. */
        Resource: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        /** @description JSON collection response. */
        Collection: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data?: {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
        /** @description Paginated JSON collection response. */
        PaginatedCollection: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data?: {
                        [key: string]: unknown;
                    }[];
                    meta?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    parameters: {
        CompanyId: string;
        ExternalId: string;
        IdempotencyKey: string;
        DocumentTypeQuery: "nfe" | "nfce" | "nfse";
        MunicipioQuery: string;
        FiscalEnvironmentQuery: "homologacao" | "producao" | "production" | "prod";
    };
    requestBodies: {
        JsonObject: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        DocumentPreview: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        DocumentSubmit: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"] & Record<string, never>;
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    getCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getCompanyConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    updateCompanyConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getCompanyNfseProviderInfo: {
        parameters: {
            query?: {
                municipio?: components["parameters"]["MunicipioQuery"];
                fiscal_environment?: components["parameters"]["FiscalEnvironmentQuery"];
            };
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NFSe provider metadata and form policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["NfseProviderInfo"];
                    };
                };
            };
        };
    };
    listCompanyFiscalOperationProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createCompanyFiscalOperationProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    updateCompanyFiscalOperationProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteCompanyFiscalOperationProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listCompanyFiscalRateReferences: {
        parameters: {
            query?: {
                tax_type?: string;
                tax_situation_code?: string;
                tax_classification_code?: string;
                municipality_ibge?: string;
                uf?: string;
            };
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createCompanyFiscalRateReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    updateCompanyFiscalRateReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                rate_reference_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteCompanyFiscalRateReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                rate_reference_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listCompanyFiscalTaxRuleSets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createCompanyFiscalTaxRuleSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    updateCompanyFiscalTaxRuleSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                tax_rule_set_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteCompanyFiscalTaxRuleSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                tax_rule_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    previewCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentPreview"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listCompanyDocuments: {
        parameters: {
            query?: {
                document_type?: components["parameters"]["DocumentTypeQuery"];
            };
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PaginatedCollection"];
        };
    };
    createCompanyDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    getCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    cancelCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    correctCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    createCompanyDirectDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    transmitCompanyDirectXml: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listTakers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createTaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    getTaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                taker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    updateTaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                taker_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteTaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                taker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    rotateWebhookSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    testWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    getIntegrationMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getIntegrationBilling: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listDefaultCompanyDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PaginatedCollection"];
        };
    };
    createDefaultCompanyDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    previewDefaultCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentPreview"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getDefaultCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    cancelDefaultCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    correctDefaultCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    createDefaultCompanyDirectDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    transmitDefaultCompanyDirectXml: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    getDefaultCompanyConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    updateDefaultCompanyConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getDefaultCompanyNfseProviderInfo: {
        parameters: {
            query?: {
                municipio?: components["parameters"]["MunicipioQuery"];
                fiscal_environment?: components["parameters"]["FiscalEnvironmentQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NFSe provider metadata and form policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["NfseProviderInfo"];
                    };
                };
            };
        };
    };
}
