/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompanyConfiguration"];
        put: operations["updateCompanyConfiguration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/nfse/provider-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the dynamic NFSe form policy required by the resolved municipal provider. */
        get: operations["getCompanyNfseProviderInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/operation-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanyFiscalOperationProfiles"];
        put?: never;
        post: operations["createCompanyFiscalOperationProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/operation-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCompanyFiscalOperationProfile"];
        post?: never;
        delete: operations["deleteCompanyFiscalOperationProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/rate-references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanyFiscalRateReferences"];
        put?: never;
        post: operations["createCompanyFiscalRateReference"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/rate-references/{rate_reference_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCompanyFiscalRateReference"];
        post?: never;
        delete: operations["deleteCompanyFiscalRateReference"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/tax-rule-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanyFiscalTaxRuleSets"];
        put?: never;
        post: operations["createCompanyFiscalTaxRuleSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/fiscal/tax-rule-sets/{tax_rule_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCompanyFiscalTaxRuleSet"];
        post?: never;
        delete: operations["deleteCompanyFiscalTaxRuleSet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/{operation_code}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resolves the fiscal operation by code and previews a document from a snapshot-shaped input contract. */
        post: operations["previewCompanyDocumentByOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCompanyDocuments"];
        put?: never;
        post: operations["createCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/{operation_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resolves the fiscal operation by code and queues a document from a snapshot-shaped input contract. */
        post: operations["createCompanyDocumentByOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompanyDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/{external_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/documents/{external_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["correctCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/direct/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCompanyDirectDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/direct/documents/xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transmitCompanyDirectXml"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProducts"];
        put?: never;
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProduct"];
        put: operations["updateProduct"];
        post?: never;
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{company_id}/takers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTakers"];
        put?: never;
        post: operations["createTaker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWebhooks"];
        put?: never;
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateWebhook"];
        post?: never;
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateWebhookSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhook_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIntegrationMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIntegrationBilling"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compatibility alias for the integration client's default company. */
        get: operations["listDefaultCompanyDocuments"];
        put?: never;
        /** @description Compatibility alias for the integration client's default company. */
        post: operations["createDefaultCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compatibility alias for the integration client's default company. */
        post: operations["previewDefaultCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{operation_code}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compatibility alias for the default company. Resolves the fiscal operation by code and previews from snapshot-shaped input. */
        post: operations["previewDefaultCompanyDocumentByOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{operation_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compatibility alias for the default company. Resolves the fiscal operation by code and queues from snapshot-shaped input. */
        post: operations["createDefaultCompanyDocumentByOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefaultCompanyDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/direct/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compatibility alias for direct transmission on the integration client's default company. */
        post: operations["createDefaultCompanyDirectDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/direct/documents/xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compatibility alias for direct XML transmission on the integration client's default company. */
        post: operations["transmitDefaultCompanyDirectXml"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configuration/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefaultCompanyConfiguration"];
        put: operations["updateDefaultCompanyConfiguration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nfse/provider-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Compatibility alias for the integration client's default company. */
        get: operations["getDefaultCompanyNfseProviderInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{external_id}/xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadDefaultCompanyDocumentXml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{external_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadDefaultCompanyDocumentPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{external_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefaultCompanyDocumentSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{external_id}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["queryDefaultCompanyDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyCertificates"];
        put?: never;
        post: operations["createDefaultCompanyCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certificates/{certificate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateDefaultCompanyCertificate"];
        trace?: never;
    };
    "/certificates/{certificate_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateDefaultCompanyCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefaultCompanyReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyOnboardingImports"];
        put?: never;
        post: operations["createDefaultCompanyOnboardingImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefaultCompanyOnboardingImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/imports/{import_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewDefaultCompanyOnboardingImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/imports/{import_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["promoteDefaultCompanyOnboardingImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fiscal/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyFiscalOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fiscal/cfops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyCfops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fiscal/utils/municipalities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchDefaultCompanyMunicipalities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fiscal/utils/ncms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchDefaultCompanyNcms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fiscal/tax-catalogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyTaxCatalogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fiscal/tax-catalogs/{catalog}/situations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyTaxSituations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fiscal/tax-situations/{situation}/classifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyTaxClassifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fiscal/tax-situations/{situation}/consequence-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefaultCompanyTaxConsequenceTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consulta-notas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyUnifiedDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consulta-notas/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["lookupDefaultCompanyUnifiedDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consulta-notas/{source}/{document_id}/xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadDefaultCompanyUnifiedDocumentXml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consulta-notas/{source}/{document_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadDefaultCompanyUnifiedDocumentPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbound/nfe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyInboundNfe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbound/nfe/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["syncDefaultCompanyInboundNfe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanyStockMovements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDefaultCompanyStockBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDefaultCompanySchedules"];
        put?: never;
        post: operations["createDefaultCompanySchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DocumentRequest: {
            external_id?: string;
            /** @enum {string} */
            document_type: "nfe" | "nfce" | "nfse";
            municipio?: string;
            payload: {
                [key: string]: unknown;
            };
            metadata?: {
                [key: string]: unknown;
            };
        };
        OperationDocumentRequest: {
            external_id?: string;
            /** @enum {string} */
            document_type: "nfe" | "nfce" | "nfse";
            municipio?: string;
            snapshot: components["schemas"]["OperationDocumentSnapshot"];
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** @description Snapshot-shaped input. Fiscal resolution fields are generated by NotaAgil and must not be sent by clients. */
        OperationDocumentSnapshot: {
            document_direction?: string;
            direction?: string;
            /** @enum {string} */
            fiscal_environment?: "homologacao" | "producao";
            reference_date?: string;
            document_data?: {
                [key: string]: unknown;
            };
            counterparty?: {
                [key: string]: unknown;
            };
            document_references?: {
                [key: string]: unknown;
            }[];
            items: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        NfseProviderInfo: {
            provider_key?: string | null;
            municipio?: string | null;
            resolution_source?: string | null;
            provider_metadata?: {
                [key: string]: unknown;
            };
            warnings?: string[];
            form_policy?: components["schemas"]["NfseFormPolicy"];
        };
        NfseFormPolicy: {
            provider_key?: string | null;
            layout_family?: string | null;
            municipio_ibge?: string | null;
            municipio_nome?: string | null;
            policy_source?: string;
            required_fields?: components["schemas"]["NfsePolicyField"][];
            visible_fields?: components["schemas"]["NfsePolicyField"][];
            default_values?: {
                [key: string]: string;
            };
            field_schema?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            labels?: {
                [key: string]: string;
            };
            hints?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        NfsePolicyField: "service.municipal_code" | "service.national_tax_code" | "service.nbs" | "service.cnae_code" | "service.activity_code" | "prestador.op_simp_nac";
    };
    responses: {
        /** @description JSON resource response. */
        Resource: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        /** @description JSON collection response. */
        Collection: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data?: {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
        /** @description Paginated JSON collection response. */
        PaginatedCollection: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data?: {
                        [key: string]: unknown;
                    }[];
                    meta?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    parameters: {
        CompanyId: string;
        ExternalId: string;
        OperationCode: string;
        IdempotencyKey: string;
        DocumentTypeQuery: "nfe" | "nfce" | "nfse";
        MunicipioQuery: string;
        FiscalEnvironmentQuery: "homologacao" | "producao" | "production" | "prod";
    };
    requestBodies: {
        JsonObject: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        DocumentPreview: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"];
            };
        };
        DocumentSubmit: {
            content: {
                "application/json": components["schemas"]["DocumentRequest"] & {
                    external_id: string;
                };
            };
        };
        OperationDocumentPreview: {
            content: {
                "application/json": components["schemas"]["OperationDocumentRequest"];
            };
        };
        OperationDocumentSubmit: {
            content: {
                "application/json": components["schemas"]["OperationDocumentRequest"] & {
                    external_id: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    getCompany: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getCompanyConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    updateCompanyConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getCompanyNfseProviderInfo: {
        parameters: {
            query?: {
                municipio?: components["parameters"]["MunicipioQuery"];
                fiscal_environment?: components["parameters"]["FiscalEnvironmentQuery"];
            };
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NFSe provider metadata and form policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["NfseProviderInfo"];
                    };
                };
            };
        };
    };
    listCompanyFiscalOperationProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createCompanyFiscalOperationProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    updateCompanyFiscalOperationProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteCompanyFiscalOperationProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listCompanyFiscalRateReferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createCompanyFiscalRateReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    updateCompanyFiscalRateReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                rate_reference_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteCompanyFiscalRateReference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                rate_reference_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listCompanyFiscalTaxRuleSets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createCompanyFiscalTaxRuleSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    updateCompanyFiscalTaxRuleSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                tax_rule_set_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteCompanyFiscalTaxRuleSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                tax_rule_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    previewCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentPreview"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    previewCompanyDocumentByOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                operation_code: components["parameters"]["OperationCode"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["OperationDocumentPreview"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listCompanyDocuments: {
        parameters: {
            query?: {
                document_type?: components["parameters"]["DocumentTypeQuery"];
            };
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PaginatedCollection"];
        };
    };
    createCompanyDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    createCompanyDocumentByOperation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                company_id: components["parameters"]["CompanyId"];
                operation_code: components["parameters"]["OperationCode"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["OperationDocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    getCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    cancelCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    correctCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    createCompanyDirectDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    transmitCompanyDirectXml: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listTakers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createTaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: components["parameters"]["CompanyId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    rotateWebhookSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    testWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    getIntegrationMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getIntegrationBilling: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listDefaultCompanyDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PaginatedCollection"];
        };
    };
    createDefaultCompanyDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    previewDefaultCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentPreview"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    previewDefaultCompanyDocumentByOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_code: components["parameters"]["OperationCode"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["OperationDocumentPreview"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    createDefaultCompanyDocumentByOperation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                operation_code: components["parameters"]["OperationCode"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["OperationDocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    getDefaultCompanyDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    createDefaultCompanyDirectDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["DocumentSubmit"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    transmitDefaultCompanyDirectXml: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            202: components["responses"]["Resource"];
        };
    };
    getDefaultCompanyConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    updateDefaultCompanyConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getDefaultCompanyNfseProviderInfo: {
        parameters: {
            query?: {
                municipio?: components["parameters"]["MunicipioQuery"];
                fiscal_environment?: components["parameters"]["FiscalEnvironmentQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NFSe provider metadata and form policy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["NfseProviderInfo"];
                    };
                };
            };
        };
    };
    downloadDefaultCompanyDocumentXml: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description XML artifact. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadDefaultCompanyDocumentPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF artifact. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDefaultCompanyDocumentSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    queryDefaultCompanyDocument: {
        parameters: {
            query?: {
                force_remote?: boolean;
            };
            header?: never;
            path: {
                external_id: components["parameters"]["ExternalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listDefaultCompanyCertificates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createDefaultCompanyCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    updateDefaultCompanyCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    validateDefaultCompanyCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    getDefaultCompanyReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listDefaultCompanyOnboardingImports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createDefaultCompanyOnboardingImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
    getDefaultCompanyOnboardingImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    reviewDefaultCompanyOnboardingImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    promoteDefaultCompanyOnboardingImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listDefaultCompanyFiscalOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listDefaultCompanyCfops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    searchDefaultCompanyMunicipalities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    searchDefaultCompanyNcms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listDefaultCompanyTaxCatalogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    listDefaultCompanyTaxSituations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalog: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    listDefaultCompanyTaxClassifications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                situation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    getDefaultCompanyTaxConsequenceTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                situation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listDefaultCompanyUnifiedDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    lookupDefaultCompanyUnifiedDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    downloadDefaultCompanyUnifiedDocumentXml: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: "inbound" | "outbound";
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description XML artifact. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadDefaultCompanyUnifiedDocumentPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: "inbound" | "outbound";
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF artifact. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDefaultCompanyInboundNfe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    syncDefaultCompanyInboundNfe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            200: components["responses"]["Resource"];
        };
    };
    listDefaultCompanyStockMovements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    getDefaultCompanyStockBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    listDefaultCompanySchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Collection"];
        };
    };
    createDefaultCompanySchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["JsonObject"];
        responses: {
            201: components["responses"]["Resource"];
        };
    };
}
